storage:
  type: "database" 
  database:
    dsn: "host=localhost port=54320 user=postgres password=password dbname=postgres sslmode=disable"

limit:
  time: 10
  cpu: 1
  memory: 512

process: 4

name: "猫猫"
  
